bloggin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("authentication/", include("users.urls")),
    path("", include("mainapp.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from . import views


app_name = "mainapp"
urlpatterns = [path("", views.main_view, name="main_view"),
               path("hello/", views.hello_visitor, name="hello_visitor"),
               path("new_article/", views.new_article_view, name="new_article_view"),
               path("<str:article_url>/", views.read_article_view, name="read_article_view"), 
               path("edit/<str:article_url>/", views.edit_article_view, name="edit_article_view"),
               path("users/<str:user_username>/", views.user_profile, name="user_profile"),] 

users/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views


app_name="users"
urlpatterns = [
    path("register/", views.register, name="register_view"),
    path("", include("django.contrib.auth.urls")),]

mainapp/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


class Topic(models.Model):
    name=models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Article(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    body = RichTextField(blank=True, null=True)
    publication_date = models.DateField()
    last_edit_date = models.DateField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True, upload_to="images/")
    url = models.CharField(max_length=200, default='doesnotwork')
    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default=0)
    total_votes = models.IntegerField(default=0)
    topics = models.ManyToManyField(Topic, blank=True)
    model_name = "article"

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        words = self.title.split()[:5]
        self.url = slugify('-'.join(words).lower())
        self.total_votes = self.upvotes - self.downvotes
        super().save(*args, **kwargs)
    
    def update_total_votes(self):
        self.upvotes = ArticleVote.objects.filter(article=self, is_upvote=True).count()
        self.downvotes = ArticleVote.objects.filter(article=self, is_upvote=False).count()
        self.save()

class ArticleVote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    is_upvote = models.BooleanField()
    
    class Meta:
        unique_together = ('user', 'article')

    def save(self, *args, **kwargs):
        existing_vote = ArticleVote.objects.filter(user=self.user, article=self.article)
        if existing_vote:
            existing_vote.is_upvote = self.is_upvote
            existing_vote.save()
        else:
            super().save(*args, **kwargs)

            if self.is_upvote:
                self.article.upvotes +=1
            else:
                self.article.downvotes +=1
            self.article.save()


class Comment(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    text = models.TextField()
    publication_date = models.DateField()
    last_edit_date = models.DateField(null=True, blank=True)
    model_name = "comment"

    def __str__(self):
        return self.text
    

class Subcomment(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    parent_comment = models.ForeignKey(Comment, related_name="subcomments", on_delete=models.CASCADE)
    text = models.TextField()
    publication_date = models.DateField()
    last_edit_date = models.DateField(null=True, blank=True)
    model_name = "comment"

    def ___str___(self):
        return self.text
    

mainapp/forms.py
from django import forms
from .models import Article, Comment, Subcomment, Topic

class NewArticle(forms.ModelForm):
    topics = forms.ModelMultipleChoiceField(queryset=Topic.objects.all(), widget=forms.CheckboxSelectMultiple)
    class Meta:
        model = Article
        fields = ["title", "body","image", "topics"]

class NewComment(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]

class NewSubcomment(forms.ModelForm):
    class Meta:
        model = Subcomment
        fields=["text"]
        

mainapp/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.http import Http404, JsonResponse

from .models import Article, Comment, ArticleVote, Topic, Subcomment
from .forms import NewArticle, NewComment, NewSubcomment

def main_view(request):
    """Home page view, returns all articles ordered from the newest, list of top articles and available topics.
    """
    all_articles = Article.objects.all()[::-1]
    top_articles = Article.objects.all()[:10]
    topics = Topic.objects.all()
    return render(request, "mainapp/main.html", {"all_articles":all_articles, "top_articles":top_articles, "topics":topics})


def read_article_view(request, article_url):
    """View for displaying article content and comment/subcomment forms."""

    # Acces specific article and it's comments
    article = get_object_or_404(Article, url=article_url)
    comments = Comment.objects.filter(article=article)

    # Handling submitting a comment
    if request.method == "POST":
        comment_form = NewComment(request.POST)
        subcomment_form = NewSubcomment(request.POST)
        form_type = request.POST.get('form_type')
        if form_type == 'comment_form':
            # If submit is a comment
            if comment_form.is_valid():
                new_comment = comment_form.save(commit=False)
                new_comment.publication_date = timezone.now()
                new_comment.article = article
                new_comment.owner = request.user
                new_comment.save()            
        elif form_type == 'subcomment_form':
            # If submit is subcomment
            if subcomment_form.is_valid():
                parent_comment_id = request.POST.get('parent_comment_id')
                parent_comment = get_object_or_404(Comment, pk=parent_comment_id)
                new_subcomment = subcomment_form.save(commit=False)
                new_subcomment.publication_date = timezone.now()
                new_subcomment.article = article
                new_subcomment.owner = request.user
                new_subcomment.parent_comment = parent_comment
                new_subcomment.save()
        comment_form = NewComment()
        subcomment_form = NewSubcomment()
        return render(request, "mainapp/read_article.html", {
            "article": article,
            "comments": comments,
            "comment_form": comment_form,
            "subcomment_form": subcomment_form
        })
    else:
        # Display article and comments forms (GET request)
        comment_form = NewComment()
        subcomment_form = NewSubcomment()

    return render(request, "mainapp/read_article.html", {
        "article": article,
        "comments": comments,
        "comment_form": comment_form,
        "subcomment_form": subcomment_form
    })


@login_required
def new_article_view(request):
    """View for adding new article."""

    # Submitting article (POST request)
    if request.method == "POST":
        form = NewArticle(request.POST, request.FILES)
        if form.is_valid():
            new_article = form.save(commit=False)
            new_article.publication_date = timezone.now()
            new_article.owner = request.user
            new_article = form.save()
            return HttpResponseRedirect(reverse("mainapp:read_article_view", args=(new_article.url,)))
    #GET request
    else:
        form=NewArticle()
        return render(request, "mainapp/new_article.html", {"form":form})


@login_required
def edit_article_view(request, article_url):
    """View for editing already existing article."""

    # Acces specific article
    article = get_object_or_404(Article, url=article_url)
    # Check if user is the owner of the article, so he can edit it
    if article.owner != request.user:
        raise Http404
    # POST request
    if request.method =="POST":
        form = NewArticle(request.POST, request.FILES, instance=article)
        if form.is_valid():
            article = form.save(commit=False)
            article.last_edit_date = timezone.now()
            article = form.save()
            return HttpResponseRedirect(reverse("mainapp:read_article_view", args=(article.url,)))
    # Displaying article content in form (GET request)
    else:
        form = NewArticle(instance=article)
    return render(request, "mainapp/edit_article_view.html", {"form": form})


def user_profile(request, user_username):
    """Displaying profile of specific user, his info such as nickname, profile picture, added articles and comments."""

    # Acces user and his activities
    user = get_object_or_404(User, username = user_username)
    activities = []
    articles = Article.objects.filter(owner=user)
    comments = Comment.objects.filter(owner=user)
    subcomments = Subcomment.objects.filter(owner=user)

    # Merge articles and comments into a single list
    for item in articles:
        activities.append(item)

    for item in comments:
        activities.append(item)

    for item in subcomments:
        activities.append(item)

    # Sort activities by publication_date from newest to oldest
    if activities != []:
        activities.sort(key=lambda activity: activity.publication_date, reverse=True)
    return render(request, "mainapp/user_profile.html", {"user":user, "articles":articles, "comments":comments, "activities":activities})


def hello_visitor(request):
    """View for no exisitng/upcoming functionalities and buttons."""

    return render(request,"mainapp/hello_visitor.html", {})

mainapp/templates/mainapp/edit_article_view.html
{% extends "mainapp/new_article.html" %}
{% load widget_tweaks %}


{% block header %}
<h1>Edit article</h1>
{% endblock header %}

{% block formbutton %}
<button type="submit">Confirm changes</button>
{% endblock formbutton %}

mainapp/templates/mainapp/hello_visitor.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>bloggin</title>
    <meta name="author" content="ravdar">
    <link rel="icon" type="image/x-icon" href="{% static 'icons/bloggin-icon.ico' %}">
    <meta name="description" content="Template for upcoming/not exisitng functionalities.">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>


<body class="center">
    <div class="hello-visitor center">
        <h1 style="color:green">Hello, visitor!</h1>
        <p>Since this project is mainly for my portfolio right now, some features like topics are just for show. You
            might
            have clicked on one of those. If you'd like to explore the actual application, click the button below.
            Enjoy!
        </p>
        <a href="{% url 'mainapp:main_view' %}"><button>Go to the main page</button></a>
    </div>

    <script>console.log("Hire me, please")</script>

</body>

</html>

mainapp/templates/mainapp/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="ravdar">
    <meta name="description" content="Main page for 'bloggin' website.">
    <title>bloggin</title>
    <link rel="icon" type="image/x-icon" href="{% static 'icons/bloggin-icon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <script defer src="{% static 'main.js' %}"></script>

</head>

<body>
    <header class="center">
        <div class="header-content">
            <a href="{% url 'mainapp:main_view' %}" class="logotype">bloggin.</a>
            <div class="header-buttons">
                {% if request.user.is_authenticated %}
                <button><a class="button-a" href="{% url 'mainapp:new_article_view' %}">New article</a></button>
                <form action="{% url 'users:logout' %}" method="post">
                    {% csrf_token %}
                    <button class="logout-button" type="submit">Log out</button>
                </form>
                <a href="{% url 'mainapp:user_profile' user.username %}"><img class="profile-picture-radius" width="30"
                        height="30" loading="lazy" alt="Profile picture"
                        src="{{ request.user.profile.profile_picture.url }}"></a>
                {% else %}
                <a href="{% url 'users:login' %}">Login</a>
                <button><a class="button-a" href="{% url 'users:register_view' %}">Register</a></button>
                {% endif %}
            </div>
        </div>
    </header>

    {% block content %}
    <main>
        <section class="topics">
            {% for topic in topics %}
            <a href="{% url 'mainapp:hello_visitor' %}"><button class="topic-button">{{topic.name}}</button></a>
            {% endfor %}
        </section>

        <!-- wrapper needed for responsive desing -->
        <section class="trending-and-new-articles">
            <section class="trending-section">
                <div class="trending-header center">
                    <h3>Trending articles</h3><button class="trending-button">+</button>
                </div>
                <div class="trending-articles">
                    {% for trending_article in top_articles %}
                    <div>
                        <div class="author-and-date">
                            <div class="author center"><a
                                    href="{% url 'mainapp:user_profile' trending_article.owner.username %}"><img
                                        src="{{trending_article.owner.profile.profile_picture.url}}"
                                        alt="Profile picture" height="20" width="20" loading="lazy"></a>
                                <a
                                    href="{% url 'mainapp:user_profile' trending_article.owner.username %}">{{trending_article.owner.username}}</a>
                            </div>{{trending_article.publication_date}}
                        </div><a
                            href="{% url 'mainapp:read_article_view' trending_article.url %}">{{trending_article.title}}</a>
                    </div>
                    {% endfor %}
                </div>
            </section>

            <section class="new-articles">
                {% for article in all_articles %}
                <div class="article-info">
                    <div class="author-and-date">
                        <div class="author center"><a
                                href="{% url 'mainapp:user_profile' article.owner.username %}"><img
                                    src="{{article.owner.profile.profile_picture.url}}" alt="Profile picture"
                                    height="20" width="20"></a>
                            <a
                                href="{% url 'mainapp:user_profile' article.owner.username %}">{{article.owner.username}}</a>
                        </div>{{article.publication_date}}
                    </div>
                    <a
                            href="{% url 'mainapp:read_article_view' article.url %}"><div class="article-picture-wrapper"><img src="{{ article.image.url }}"
                                alt="Article image" width="330" height="200" loading="lazy"></div></a>
                    <h4><a href="{% url 'mainapp:read_article_view' article.url %}">{{article.title}}</a>
                    </h4>
                    <p>{{ article.body|safe|slice:":100"}}...</p>
                </div>
                {% endfor %}
            </section>
        </section>
    </main>
    {% endblock content %}

    <footer class="center">
        &copy 2024 ravdar
        <br>
        All rights reserved
    </footer>

</body>

</html>

mainapp/templates/mainapp/new_article.html
{% extends "mainapp/main.html" %}
{% load widget_tweaks %}

{% block content %}

<main class="margin-top-main center">
    {% block header %}
    <h1>Write a new article</h1>
    {% endblock header %}
    &nbsp;
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form.title|add_class:"new-article-inputs"|attr:"placeholder:Title"}}
        {{form.body|add_class:"new-article-inputs"}}
        &nbsp;
        <div class="image-and-topics-container">
            <label for="{{ form.image.id }}">Select article image</label>
            {{form.image}}
            <div class="select-topics"><label for="{{ form.topics.id }}">Select topics</label><button id="show-topics"
                    class="topics-button" type="button">+</button>
                <div class="available-topics">
                    {{form.topics}}</div>
            </div>
        </div>
        {% block formbutton %}
        <button type="submit">Submit</button>
        {% endblock formbutton %}

    </form>
</main>

{% endblock content %}

mainapp/templates/mainapp/read_article.html
{% extends "mainapp/main.html" %}
{% load widget_tweaks %}

{%block content %}
<main class="read-article-main center">
    <!-- Article display -->
    <section class="article-display">
        <img src="{{ article.image.url }}" alt="Article image">
        <br>
        <div class="author-and-date">
            <div class="author center"><a href="{% url 'mainapp:user_profile' article.owner.username %}"><img
                        src="{{article.owner.profile.profile_picture.url}}" alt="Profile picture" height="20"
                        width="20"></a>
                <a href="{% url 'mainapp:user_profile' article.owner.username %}">{{article.owner.username}}</a>
                {% if article.owner == user %}
                <a href="{% url 'mainapp:edit_article_view' article.url %}">Edit</a>
                {% endif %}
            </div>{{article.publication_date}}
        </div>
        <article>
            <h1>{{article.title}}</h1>
            &nbsp;
            <p>{{article.body|safe}}</p>
        </article>
    </section>

    <!-- Comments section -->
    <section class="comments">
        <!-- Add comment form -->
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="form_type" value="comment_form">
            {{comment_form.text|add_class:"form-control wid"|attr:"placeholder:What are your thoughts on this topic?"}}
            {% if user.is_authenticated %}
            <button type="submit">Submit</button>
            {% else %}
            <p>You have to be <span><a href="{% url 'users:login' %}">logged</a></span> to
                post comments.</p>
            {% endif %}
            <br>
        </form>
        <!-- Displaying all comments -->
        {% for comment in comments %}
        <div class="comment-container">
            <div class="author-and-date">
                <div class="author center">
                    <a href="{% url 'mainapp:user_profile' comment.owner.username %}"><img
                            src="{{comment.owner.profile.profile_picture.url}}" class="profile-picture-radius"
                            width="20px" height="20px" loading="lazy" alt="Profile picture"></a>
                    <a href="{% url 'mainapp:user_profile' comment.owner.username %}">
                        {{comment.owner.username}}
                    </a>
                </div>
                {{comment.publication_date}}
            </div>
            <br>
            <p>{{comment.text}}</p>
            <br>
            <div class="comment-tools">
                {% if comment.owner == user %}
                <a href="{% url 'mainapp:edit_article_view' article.url %}">Edit</a>
                {% endif %}
                Upvote
                Downvote
                <button onclick="displaySubcommentForm('{{ comment.id }}')">Reply</button>
            </div>
            <!-- Subcomment form, displayed only after clicking "Reply" button -->
            <form id="subcomment-form{{ comment.id }}" class="subcomment-form" method="post">
                {% csrf_token %}
                <input type="hidden" name="form_type" value="subcomment_form">
                <input type="hidden" name="parent_comment_id" value="{{ comment.id }}">
                <textarea name="text" class="form-control wid" placeholder="Answer"></textarea>
                {% if user.is_authenticated %}
                <button type="submit">Submit</button>
                {% else %}
                <p>You have to be <span><a href="{% url 'users:login' %}">logged</a></span> to
                    reply to comments.</p>
                {% endif %}
            </form>
            <!-- All comment subcomments -->
            {% for subcomment in comment.subcomments.all %}
            <div class="comment-container">
                <div class="author-and-date">
                    <div class="author center">
                        <a href="{% url 'mainapp:user_profile' subcomment.owner.username %}"><img
                                src="{{subcomment.owner.profile.profile_picture.url}}" class="profile-picture-radius"
                                width="20px" height="20px" loading="lazy" alt="Profile picture"></a>
                        <a href="{% url 'mainapp:user_profile' subcomment.owner.username %}">
                            {{subcomment.owner.username}}
                        </a>
                    </div>
                    {{subcomment.publication_date}}
                </div>
                <br>
                <p>{{subcomment.text}}</p>
                <br>
                <div class="comment-tools">
                    {% if subcomment.owner == user %}
                    <a href="{% url 'mainapp:edit_article_view' article.url %}">Edit</a>
                    {% endif %}
                    Upvote
                    Downvote
                    <button onclick="displaySubcommentForm('{{ comment.id }}')">Reply</button>
                </div>
                <!-- Subcomment form, displayed only after clicking "Reply" button -->
                <form id="subcomment-form{{ comment.id }}" class="subcomment-form" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="form_type" value="subcomment_form">
                    <input type="hidden" name="parent_comment_id" value="{{ comment.id }}">
                    <textarea name="text" class="form-control wid" placeholder="Answer"></textarea>
                    {% if user.is_authenticated %}
                    <button type="submit">Submit</button>
                    {% else %}
                    <p>You have to be <span><a href="{% url 'users:login' %}">logged</a></span> to
                        reply to comments.</p>
                    {% endif %}
                </form>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </section>
</main>

{% endblock content %}

mainapp/templates/mainapp/user_profile.html
{% extends "mainapp/main.html" %}

{% block content %}

<main class="margin-top-main center">
    <section class="profile-basic-info center">
        <img src="{{ user.profile.profile_picture.url}}" alt="Profile picture" height="80" width="80">
        <h2>{{user.username}}</h2>
        <div>
            <a href="{% url 'mainapp:user_profile' user.username %}">Overview</a>
            <a href="{% url 'mainapp:user_profile' user.username %}">Articles</a>
            <a href="{% url 'mainapp:user_profile' user.username %}">Comments</a>
        </div>
    </section>
    <section class="user-activities">
        {% for activity in activities %}
        <div>
            {% if activity.model_name == "article" %}
            <time>{{activity.publication_date}}</time>
            <p>Posted article:</p>
            <a href="{% url 'mainapp:read_article_view' activity.url %}"><img src="{{ activity.image.url }}" width="140"
                    height="80"></a>
            <h4><a href="{% url 'mainapp:read_article_view' activity.url %}">{{activity.title}}</a>
            </h4>
            <p>{{ activity.body|slice:":100"|safe }}...</p>
            {% else %}
            <time>{{activity.publication_date}}</time>
            <p>Added comment to <a
                    href="{% url 'mainapp:read_article_view' activity.article.url %}"><span>{{activity.article.title}}</span></a>
            </p>
            {{activity.text|slice:":100"|safe}}
            {% endif %}
        </div>
        {% endfor %}
    </section>
</main>

{% endblock content %}